"""engine.py — Facade re-exporting from split engine modules (P0 refactor)."""
from __future__ import annotations

# Re-export from engine_core.py
from trinity.modules.second_brain.engine_core import (
    VERSION, PAPERS, SEP, SUB,
    GovernanceState,
    ContextNestVerifiableGovernance,
    ContinuityState,
    RelationalVersioning,
    ProgressiveCascade,
    SelfOptimizingMemory,
    ElephantAgentStateContinuity,
    ValueCategoryMapping,
    ReasoningDriftAuditor,
    HippocampalComplementaryMemory,
    ContextObjectManager,
    SecondBrainV636,
    ExecutionGear,
    ConstraintSteerableOversight,
    RetrievalSystemV47,
    MemoryErrorType,
    IdentityPreservingConsolidator,
    MultiHeadRecurrentMemory,
    TemporalValidity,
    TokenEfficientMemory,
    ContextAction,
    OnlineSafetyMonitor,
    ContextObject,
    ContextualChunkIngestion,
    AgentNativeCuration,
    MemoryHead,
    MultiHeadMemoryPartition,
    ThreeLayerHierarchicalMemory,
    ContextCommit,
    ExactKVEntry,
    CacheWriteDecision,
    ConsolidationPhase,
    ProvenanceRecord,
    SafetyAlarm,
    ConsolidationRecord,
    GuardianChainV50,
    CertificateStatus,
)

# Retrieval subsystem
from trinity.modules.second_brain.engine_retrieval import (
    ExabaseRetrieval,
    BEAMLIGHT,
)

# Observability subsystem
from trinity.modules.second_brain.engine_observability import (
    EntityEntry,
    ZikkaronHopfield,
    ActivationNode,
    QueryType,
    HindsightFourNetwork,
    NetworkType,
    VectorEntry,
    GraphEdge,
    HopfieldMemory,
    ObserverReflector,
    TemporalEntry,
    SpreadingActivationGraph,
)

# Diagnostics subsystem
from trinity.modules.second_brain.engine_diagnostics import (
    GroundTruthEpisodes,
)

# Total: 52 classes + VERSION, PAPERS, SEP, SUB
__all__ = [
    "VERSION",
    "PAPERS",
    "SEP",
    "SUB",
    "ContextAction",
    "ExecutionGear",
    "GovernanceState",
    "CertificateStatus",
    "MemoryErrorType",
    "CacheWriteDecision",
    "ConsolidationPhase",
    "ContextObject",
    "ContextCommit",
    "MemoryHead",
    "ProvenanceRecord",
    "ContinuityState",
    "SafetyAlarm",
    "ExactKVEntry",
    "ConsolidationRecord",
    "ValueCategoryMapping",
    "MultiHeadRecurrentMemory",
    "ContextNestVerifiableGovernance",
    "ElephantAgentStateContinuity",
    "ConstraintSteerableOversight",
    "OnlineSafetyMonitor",
    "HippocampalComplementaryMemory",
    "IdentityPreservingConsolidator",
    "ReasoningDriftAuditor",
    "ContextObjectManager",
    "MultiHeadMemoryPartition",
    "ThreeLayerHierarchicalMemory",
    "ProgressiveCascade",
    "TemporalValidity",
    "TokenEfficientMemory",
    "AgentNativeCuration",
    "RelationalVersioning",
    "ContextualChunkIngestion",
    "ObserverReflector",
    "GroundTruthEpisodes",
    "BEAMLIGHT",
    "ExabaseRetrieval",
    "GuardianChainV50",
    "RetrievalSystemV47",
    "NetworkType",
    "QueryType",
    "VectorEntry",
    "EntityEntry",
    "TemporalEntry",
    "GraphEdge",
    "HindsightFourNetwork",
    "HopfieldMemory",
    "ActivationNode",
    "SpreadingActivationGraph",
    "ZikkaronHopfield",
    "SelfOptimizingMemory",
    "SecondBrainV636",
]
