# -*- coding: utf-8 -*-
"""t107/G4 · D-9 **成对对抗集**：求助语境 ↔ 公益/知识语境（同一主题、只差语境）。

## 定义与口径（⭐ **测量前锁定**，原文见 `G4-D9-HELPSEEKING-VS-PUBLIC.md` §1）
- **求助语境（help_seeking）**：文本的**主体是"我/我的身边人"**，且表达**当下或既往的个人危机/处境**
  （自伤轻生、法律处境、精神诊断、性史、未成年身份信息等）。
  ⇒ 设计意图明确要求：**这类内容不落库**（`high` ⇒ 拒存）。
- **公益/知识语境（public_info）**：同一主题，但文本的**主体是知识/他人/作品/统计/政策**——
  报道、科普、教材、指南、影评剧名、研究、政策条文、组织介绍。
  ⇒ **这类内容不该被拒存**（顶多 medium 标记）。
- **判定边界**：只看"**是谁的处境**"+"**文本在做什么**"（记录/求助 vs 描述/传播/预防）；
  **不看**主题词本身。**同一主题的两条文本必须给出相反结论**——这就是本集要测的"**成对区分率**"。

## 来源（每条都标 `src`，**自造已标明，不冒充官方口径**）
- `authored`：**自造**（我按上面的定义写的成对样本）
- `t70fp#N`：`evidence/t70-fp-set.json` 的第 N 条（**LongMemEval-S 前 5 万条里改前被判 high 的真实文本**，
  逐条人判为误报 ⇒ 真实**公益/知识**语境）——其 pair 的求助侧为 `authored`
- `corpus+x`：语料片段（节选，标注 `x`）

⚠️ 口径：**成对集是"判据的靶子"，不是产品数据**；它**不进**任何库、不参与生产判定。
"""
from __future__ import annotations

from typing import Any, Dict, List

#: 成对集：`help` = 求助语境（应 high/拒存）；`public` = 公益/知识语境（不应 high）。
#: 结构：{pair_id, topic, help, public, src}
PAIRS: List[Dict[str, Any]] = [
    # ── 1-12 自伤/轻生 ───────────────────────────────────────────────
    {"pair_id": "sh-01", "topic": "self_harm", "src": "authored",
     "help": "我想自杀，活着太累了。", "public": "这篇科普讲了自杀预防热线的运营流程。"},
    {"pair_id": "sh-02", "topic": "self_harm", "src": "authored",
     "help": "我最近总想结束自己的生命。", "public": "研究显示，自杀预防宣传能降低区域自杀率。"},
    {"pair_id": "sh-03", "topic": "self_harm", "src": "authored",
     "help": "我准备自杀，遗书已经写好了。", "public": "教材里提到自杀风险评估的量表有哪几种。"},
    {"pair_id": "sh-04", "topic": "self_harm", "src": "authored",
     "help": "I want to kill myself, I can't take it anymore.", "public": "This article reviews suicide prevention programs in schools."},
    {"pair_id": "sh-05", "topic": "self_harm", "src": "authored",
     "help": "She has been cutting herself again.", "public": "影评提到剧中角色自残的桥段拍得很克制。"},
    {"pair_id": "sh-06", "topic": "self_harm", "src": "authored",
     "help": "我不想活了，每天醒来都很绝望。", "public": "新闻：某地开通 24 小时心理援助热线。"},
    {"pair_id": "sh-07", "topic": "self_harm", "src": "authored",
     "help": "我老公上个月自杀未遂，我不知道怎么办。", "public": "世界卫生组织建议媒体谨慎报道自杀事件。"},
    {"pair_id": "sh-08", "topic": "self_harm", "src": "authored",
     "help": "我有自残的冲动，已经割过手腕两次。", "public": "统计显示青少年自残行为与网络使用时长相关。"},
    {"pair_id": "sh-09", "topic": "self_harm", "src": "authored",
     "help": "我昨天吞了安眠药，被送去急诊。", "public": "该药品说明书列出了过量服用的风险。"},
    {"pair_id": "sh-10", "topic": "self_harm", "src": "authored",
     "help": "我打过自杀干预热线，接电话的人劝了我很久。", "public": "文档说明自杀干预热线的排班与培训要求。"},
    {"pair_id": "sh-11", "topic": "self_harm", "src": "authored",
     "help": "我朋友说他不想活了，我该怎么陪他。", "public": "公益组织发布《如何陪伴有自杀风险的人》手册。"},
    {"pair_id": "sh-12", "topic": "self_harm", "src": "authored",
     "help": "I've been thinking about ending my life every night.", "public": "The report lists suicide rates by age group."},
    # ── 13-26 法律处境 ──────────────────────────────────────────────
    {"pair_id": "lg-01", "topic": "legal_status", "src": "authored",
     "help": "我弟弟去年进了监狱，家里一直瞒着。", "public": "新闻：该监狱因超员被监管部门通报。"},
    {"pair_id": "lg-02", "topic": "legal_status", "src": "authored",
     "help": "我自己有吸毒记录，找工作很受影响。", "public": "文章介绍吸毒记录对再就业的影响机制。"},
    {"pair_id": "lg-03", "topic": "legal_status", "src": "authored",
     "help": "我老公有案底，孩子政审过不了。", "public": "政策解读：案底与政审的法律规定有哪些。"},
    {"pair_id": "lg-04", "topic": "legal_status", "src": "authored",
     "help": "I was arrested last year and spent three months in jail.", "public": "Nelson Mandela was imprisoned from 1962 to 1990, a total of 28 years."},
    {"pair_id": "lg-05", "topic": "legal_status", "src": "authored",
     "help": "My brother has a criminal record, so he can't get a visa.", "public": "millions of people were arrested, imprisoned, and executed on trumped-up charges."},
    {"pair_id": "lg-06", "topic": "legal_status", "src": "authored",
     "help": "我儿子被判缓刑了，单位还不知道。", "public": "法条：缓刑的适用条件与考察期限。"},
    {"pair_id": "lg-07", "topic": "legal_status", "src": "authored",
     "help": "我前夫在服刑，孩子的抚养权在我这。", "public": "该剧讲一个服刑人员出狱后重新融入社会的故事。"},
    {"pair_id": "lg-08", "topic": "legal_status", "src": "authored",
     "help": "我被拘留过 15 天，会影响考公吗。", "public": "文章梳理行政拘留与刑事处罚的区别。"},
    {"pair_id": "lg-09", "topic": "legal_status", "src": "authored",
     "help": "我表弟进过看守所，现在想考驾照。", "public": "看守所的管理规范包括哪些内容。"},
    {"pair_id": "lg-10", "topic": "legal_status", "src": "authored",
     "help": "my immigration status is pending and I'm scared", "public": "everyone has access to quality healthcare, regardless of their immigration status."},
    {"pair_id": "lg-11", "topic": "legal_status", "src": "authored",
     "help": "我女儿被性骚扰过，我们报了警。", "public": "该报告统计了职场性骚扰的举报率。"},
    {"pair_id": "lg-12", "topic": "legal_status", "src": "authored",
     "help": "我朋友是无证移民，最近很焦虑。", "public": "报道：各国无证移民政策的比较。"},
    {"pair_id": "lg-13", "topic": "legal_status", "src": "authored",
     "help": "我因为酒驾被吊销驾照了。", "public": "统计：酒驾查处数量逐年变化趋势。"},
    {"pair_id": "lg-14", "topic": "legal_status", "src": "authored",
     "help": "我老公被拘留了，家里乱了。", "public": "讲述刑事拘留程序的普法文章。"},
    # ── 27-40 精神心理 ──────────────────────────────────────────────
    {"pair_id": "ph-01", "topic": "psych_health", "src": "authored",
     "help": "我得了抑郁症，正在吃药。", "public": "研究显示抑郁症患者的睡眠结构存在差异。"},
    {"pair_id": "ph-02", "topic": "psych_health", "src": "authored",
     "help": "I was diagnosed with bipolar disorder in 2021.", "public": "This article explains how bipolar disorder is diagnosed."},
    {"pair_id": "ph-03", "topic": "psych_health", "src": "authored",
     "help": "我去年住院治疗过精神分裂症。", "public": "该综述总结了精神分裂症的住院治疗指征。"},
    {"pair_id": "ph-04", "topic": "psych_health", "src": "authored",
     "help": "医生说我孩子确诊了焦虑症。", "public": "科普：儿童焦虑症的早期识别信号。"},
    {"pair_id": "ph-05", "topic": "psych_health", "src": "authored",
     "help": "我强迫症很严重，每天洗手几十次。", "public": "教材里强迫症的诊断标准与鉴别诊断。"},
    {"pair_id": "ph-06", "topic": "psych_health", "src": "authored",
     "help": "我妈妈有创伤后应激障碍，睡不好。", "public": "该研究比较了 PTSD 的两种干预方案。"},
    {"pair_id": "ph-07", "topic": "psych_health", "src": "authored",
     "help": "我在接受心理治疗，每周一次。", "public": "文章介绍心理治疗的常见流派。"},
    {"pair_id": "ph-08", "topic": "psych_health", "src": "authored",
     "help": "我确诊了进食障碍，很痛苦。", "public": "统计：进食障碍在青少年中的发病率。"},
    {"pair_id": "ph-09", "topic": "psych_health", "src": "authored",
     "help": "I'm on medication for depression and it makes me sleepy.", "public": "medication for depression is reviewed in this guideline."},
    {"pair_id": "ph-10", "topic": "psych_health", "src": "authored",
     "help": "我躁郁症发作过三次，家人很担心。", "public": "该课程讲躁郁症的社会污名问题。"},
    {"pair_id": "ph-11", "topic": "psych_health", "src": "authored",
     "help": "我孩子被诊断为自闭症谱系。", "public": "政策文件谈自闭症儿童的教育支持。"},
    {"pair_id": "ph-12", "topic": "psych_health", "src": "authored",
     "help": "我得了双相情感障碍，怕被同事知道。", "public": "纪录片讲述双相情感障碍患者的生活。"},
    {"pair_id": "ph-13", "topic": "psych_health", "src": "authored",
     "help": "我姐姐产后抑郁很严重。", "public": "科普：产后抑郁的筛查工具。"},
    {"pair_id": "ph-14", "topic": "psych_health", "src": "authored",
     "help": "我自己有焦虑症，坐飞机特别难受。", "public": "该指南给出了焦虑症的用药建议。"},
    # ── 41-48 性史 ─────────────────────────────────────────────────
    {"pair_id": "sx-01", "topic": "sexual_history", "src": "authored",
     "help": "我的性史比较复杂，有过多个性伴侣。", "public": "教材讲解性史采集在门诊中的规范流程。"},
    {"pair_id": "sx-02", "topic": "sexual_history", "src": "authored",
     "help": "She told me about her sexual history during the intake.", "public": "The survey collected data on sexual history disclosure rates."},
    {"pair_id": "sx-03", "topic": "sexual_history", "src": "authored",
     "help": "我有过一夜情，没告诉过伴侣。", "public": "文章讨论一夜情在社会学里的研究视角。"},
    {"pair_id": "sx-04", "topic": "sexual_history", "src": "authored",
     "help": "我做过人流，一直没跟家里说。", "public": "公共卫生报告统计人流的区域分布。"},
    {"pair_id": "sx-05", "topic": "sexual_history", "src": "authored",
     "help": "我伴侣有性病史，我也去查了。", "public": "该指南规定性病的报告与随访要求。"},
    {"pair_id": "sx-06", "topic": "sexual_history", "src": "authored",
     "help": "我出轨过，现在很后悔。", "public": "小说里对出轨的描写引发讨论。"},
    {"pair_id": "sx-07", "topic": "sexual_history", "src": "authored",
     "help": "我的性经历里有被强迫的部分。", "public": "研究：性暴力的报案与援助机制。"},
    {"pair_id": "sx-08", "topic": "sexual_history", "src": "authored",
     "help": "我做过性别重置手术。", "public": "政策文件关于性别重置手术的医疗规范。"},
    # ── 49-58 未成年身份信息 ────────────────────────────────────────
    {"pair_id": "mn-01", "topic": "minors_pii", "src": "authored",
     "help": "我孩子未满18岁，身份证号是 110101200801011234。", "public": "文章说明未成年人身份证号的编码规则。"},
    {"pair_id": "mn-02", "topic": "minors_pii", "src": "authored",
     "help": "My son is a minor; his school is 朝阳实验小学。", "public": "报道称多所学校提高了课后服务时长。"},
    {"pair_id": "mn-03", "topic": "minors_pii", "src": "authored",
     "help": "女儿不满16岁，学籍号 2019BJ0088，班主任姓王。", "public": "教材介绍学籍号的全国统一编码结构。"},
    {"pair_id": "mn-04", "topic": "minors_pii", "src": "authored",
     "help": "我孩子的学校地址是海淀区某某路 12 号。", "public": "该政策规定了学校地址变更的备案流程。"},
    {"pair_id": "mn-05", "topic": "minors_pii", "src": "authored",
     "help": "我儿子就读的班级有 32 个孩子。", "public": "统计：全国义务教育班级规模分布。"},
    {"pair_id": "mn-06", "topic": "minors_pii", "src": "authored",
     "help": "我女儿的护照号是 E12345678。", "public": "文章讲解护照号码的格式与有效期。"},
    {"pair_id": "mn-07", "topic": "minors_pii", "src": "authored",
     "help": "我孩子的监护人是外婆，联系电话 13800001111。", "public": "法条：监护人变更的申请材料清单。"},
    {"pair_id": "mn-08", "topic": "minors_pii", "src": "authored",
     "help": "我孩子才 12 岁，在 XX 中学读初一。", "public": "新闻：初中入学年龄的政策调整。"},
    {"pair_id": "mn-09", "topic": "minors_pii", "src": "authored",
     "help": "我女儿的住址是朝阳区某某小区 3 号楼。", "public": "该指南说明住址信息在医疗记录中的脱敏要求。"},
    {"pair_id": "mn-10", "topic": "minors_pii", "src": "authored",
     "help": "我孙子的身份证号我记在备忘录里了。", "public": "研究：身份证号在公开数据中的泄露风险。"},
    # ── 59-70 疾病/健康（一般） ─────────────────────────────────────
    {"pair_id": "hl-01", "topic": "health", "src": "authored",
     "help": "我确诊了糖尿病，每天打胰岛素。", "public": "指南：2 型糖尿病的分级诊疗路径。"},
    {"pair_id": "hl-02", "topic": "health", "src": "authored",
     "help": "我爸是肺癌晚期，家里在商量要不要化疗。", "public": "研究比较了肺癌晚期两种化疗方案。"},
    {"pair_id": "hl-03", "topic": "health", "src": "authored",
     "help": "我感染了 HIV，正在接受抗病毒治疗。", "public": "该报告统计了 HIV 抗病毒治疗的覆盖率。"},
    {"pair_id": "hl-04", "topic": "health", "src": "authored",
     "help": "我怀孕 12 周，有过流产史。", "public": "科普：孕早期流产的医学原因。"},
    {"pair_id": "hl-05", "topic": "health", "src": "authored",
     "help": "我自己有乙肝，怕公司体检查出来。", "public": "政策：入职体检不得查乙肝五项。"},
    {"pair_id": "hl-06", "topic": "health", "src": "authored",
     "help": "我妈妈阿尔茨海默病中期，需要人全天看护。", "public": "文章介绍阿尔茨海默病的照护资源。"},
    {"pair_id": "hl-07", "topic": "health", "src": "authored",
     "help": "我做过心脏支架手术。", "public": "该综述总结心脏支架术后用药。"},
    {"pair_id": "hl-08", "topic": "health", "src": "authored",
     "help": "我孩子有哮喘，换季就发作。", "public": "科普：儿童哮喘的诱因与家庭管理。"},
    {"pair_id": "hl-09", "topic": "health", "src": "authored",
     "help": "我自己有癫痫病史，能考驾照吗。", "public": "法规：癫痫患者申领驾照的条件。"},
    {"pair_id": "hl-10", "topic": "health", "src": "authored",
     "help": "我确诊了强直性脊柱炎。", "public": "研究：强直性脊柱炎的生物制剂疗效。"},
    {"pair_id": "hl-11", "topic": "health", "src": "authored",
     "help": "我老公做了胃切除手术。", "public": "指南：胃切除术后营养管理。"},
    {"pair_id": "hl-12", "topic": "health", "src": "authored",
     "help": "我有慢性肾病三期。", "public": "统计：慢性肾病的分期标准与人群分布。"},
    # ── 71-80 债务/失业/家庭 ────────────────────────────────────────
    {"pair_id": "fn-01", "topic": "finance", "src": "authored",
     "help": "我信用卡逾期三个月，被催收打电话到公司。", "public": "报道：信用卡逾期催收的合规边界。"},
    {"pair_id": "fn-02", "topic": "finance", "src": "authored",
     "help": "我欠了网贷 20 万，快撑不住了。", "public": "文章介绍网贷利率的司法保护上限。"},
    {"pair_id": "fn-03", "topic": "finance", "src": "authored",
     "help": "我失业半年了，靠借钱生活。", "public": "统计数据：城镇调查失业率的月度变化。"},
    {"pair_id": "fn-04", "topic": "finance", "src": "authored",
     "help": "我家被强制执行了，房子要拍卖。", "public": "普法：强制执行的程序与救济途径。"},
    {"pair_id": "fn-05", "topic": "finance", "src": "authored",
     "help": "我破产了，正在申请个人破产。", "public": "报道：个人破产制度试点地区的案例。"},
    {"pair_id": "fn-06", "topic": "finance", "src": "authored",
     "help": "我老婆要跟我离婚，正在争孩子抚养权。", "public": "法条：离婚时抚养权归属的判定原则。"},
    {"pair_id": "fn-07", "topic": "finance", "src": "authored",
     "help": "我被家暴过，正在申请人身安全保护令。", "public": "指南：人身安全保护令的申请流程。"},
    {"pair_id": "fn-08", "topic": "finance", "src": "authored",
     "help": "我孩子在学校被霸凌，我不敢跟老师说。", "public": "政策：校园欺凌的认定与处置流程。"},
    {"pair_id": "fn-09", "topic": "finance", "src": "authored",
     "help": "我有赌博成瘾，输了所有积蓄。", "public": "研究：赌博成瘾的干预方案比较。"},
    {"pair_id": "fn-10", "topic": "finance", "src": "authored",
     "help": "我酗酒很多年了，家里人放弃了。", "public": "科普：酒精使用障碍的诊断标准。"},
    # ── 81-92 语料侧（public 侧为 t70 真实误报文本）──────────────────
    {"pair_id": "cp-01", "topic": "legal_status", "src": "t70fp#1",
     "help": "我在追一部叫《Arrested Development》的剧，但我自己去年被捕过。",
     "public": '2. **Arrested Development** (Netflix): A witty, satirical comedy about a dysfunctional family.'},
    {"pair_id": "cp-02", "topic": "legal_status", "src": "t70fp#9",
     "help": "我家因为是低种姓，一直被歧视。",
     "public": "However, his attitudes towards Black Africans and his support for the caste system have been criticized."},
    {"pair_id": "cp-03", "topic": "legal_status", "src": "t70fp#14",
     "help": "我在印度，我的种姓让我很难找工作。",
     "public": "The caste system divides people into social groups based on their birth or occupation."},
    {"pair_id": "cp-04", "topic": "legal_status", "src": "t70fp#20",
     "help": "我朋友被定罪了，我们想申请特赦。",
     "public": "The President can pardon, commute or remit the punishment of any person convicted of an offense."},
    {"pair_id": "cp-05", "topic": "legal_status", "src": "t70fp#40",
     "help": "我爷爷在 1930 年代被逮捕过。",
     "public": "Stalin's massive purges of the 1930s, in which millions of people were arrested, imprisoned, and executed."},
    {"pair_id": "cp-06", "topic": "legal_status", "src": "t70fp#52",
     "help": "我的移民身份还在审理，很怕被拒。",
     "public": "everyone has access to quality healthcare, regardless of their immigration status."},
    {"pair_id": "cp-07", "topic": "legal_status", "src": "t70fp#55",
     "help": "我被定罪过一次，航空公司背调过不去。",
     "public": "Delta Air Lines conducts background checks on their employees who have been convicted of certain crimes."},
    {"pair_id": "cp-08", "topic": "legal_status", "src": "t70fp#65",
     "help": "我去过那座城堡，我在里面被关过几天。",
     "public": "cells of Doge's Palace are famously known for being where Casanova was imprisoned."},
    {"pair_id": "cp-09", "topic": "legal_status", "src": "t70fp#72",
     "help": "我的店铺被查封了，状态叫 arrested decay。",
     "public": 'preserved in a state of "arrested decay."'},
    {"pair_id": "cp-10", "topic": "legal_status", "src": "t70fp#82",
     "help": "我有一个很长的犯罪记录，找工作难。",
     "public": "He has a long criminal record, but this is the first time he's been connected to something."},
    {"pair_id": "cp-11", "topic": "legal_status", "src": "t70fp#101",
     "help": "我祖先当年被逮捕并处决了。",
     "public": "he was eventually arrested and executed by King Herod."},
    {"pair_id": "cp-12", "topic": "legal_status", "src": "t70fp#109",
     "help": "我自己没有被定罪，但部落的人不信我。",
     "public": "the evidence was deemed inconclusive, and Keth was not convicted."},
    # ── 93-100 语料侧（self_harm / minors / sexual 的真实误报）────────
    {"pair_id": "cp-13", "topic": "self_harm", "src": "t70fp#5",
     "help": "我一直在自残，最近更频繁了。",
     "public": "Flynn tackles mental health issues, such as depression, anxiety, and self-harm, with sensitivity."},
    {"pair_id": "cp-14", "topic": "self_harm", "src": "t70fp#21",
     "help": "我自己有抑郁和焦虑，有时会有轻生念头。",
     "public": "disorders, such as depression or anxiety, may be at a higher risk of suicide if they have access to firearms."},
    {"pair_id": "cp-15", "topic": "self_harm", "src": "t70fp#62",
     "help": "我每次训练都要做自杀式冲刺，很痛苦。",
     "public": "For cardio exercises like full-court sprints, suicide drills, and 17s, aim to do them two to three times per week."},
    {"pair_id": "cp-16", "topic": "self_harm", "src": "t70fp#69",
     "help": "我的蛋白研究里有自杀抑制机制。",
     "public": "The serpin mechanism of action involves a process called suicide inhibition."},
    {"pair_id": "cp-17", "topic": "minors_pii", "src": "t70fp#7",
     "help": "我小时候被寄养过，童年很不稳定。",
     "public": "what significant changes or challenges your family faced during your childhood, and how did you adapt?"},
    {"pair_id": "cp-18", "topic": "minors_pii", "src": "t70fp#12",
     "help": "我的孩子靠学校免费午餐。",
     "public": "Food banks provide food for kids who rely on free or reduced-price school meals."},
    {"pair_id": "cp-19", "topic": "minors_pii", "src": "t70fp#73",
     "help": "我的模型在少数类上表现很差，孩子的班级也这样。",
     "public": "Randomly duplicate samples from the minority class."},
    {"pair_id": "cp-20", "topic": "sexual_history", "src": "t70fp#92",
     "help": "我自己用过润滑剂，性体验改善很多。",
     "public": "I think lubricants are important for sexual experiences because they can make the experience more comfortable."},
    # ── 101-104 追加（教材/影视/政策/组织：纯公益侧 + 对应求助侧）──
    {"pair_id": "ex-01", "topic": "self_harm", "src": "authored",
     "help": "我女儿最近总说活着没意思，我很害怕。",
     "public": "该电视剧因涉及青少年轻生议题被列入家长指引。"},
    {"pair_id": "ex-02", "topic": "legal_status", "src": "authored",
     "help": "我哥被通缉了，他躲在我家。",
     "public": "新闻：警方通报一起通缉案件的进展。"},
    {"pair_id": "ex-03", "topic": "psych_health", "src": "authored",
     "help": "我住院治疗过重度抑郁，出院后还在吃药。",
     "public": "该医院的抑郁门诊接诊量同比上升。"},
    {"pair_id": "ex-04", "topic": "minors_pii", "src": "authored",
     "help": "我孩子 14 岁，我把他的身份证号发给你核对。",
     "public": "该文件规定了未成年人信息的处理限制。"},
]


def all_pairs() -> List[Dict[str, Any]]:
    """返回成对集（浅拷贝，防止调用方改动）。"""
    return [dict(p) for p in PAIRS]


def provenance() -> Dict[str, int]:
    """来源分布（**自造已标注**）。"""
    out: Dict[str, int] = {}
    for p in PAIRS:
        key = "authored" if p["src"] == "authored" else "corpus(t70fp)"
        out[key] = out.get(key, 0) + 1
    return out
