"""
Auto-generate second_brain/__init__.py from module files.
Scans all .py files, extracts classes/functions, generates imports.
DEPRECATED modules are commented out.
"""
import os
import re
import sys
from pathlib import Path

TARGET_DIR = Path(r"C:\Users\Administrator\trinity\trinity\modules\second_brain")
INIT_FILE = TARGET_DIR / "__init__.py"
DRY_RUN = "--dry-run" in sys.argv

def is_deprecated(filepath: Path) -> bool:
    """Check if file contains DEPRECATED marker."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read(2000)  # First 2000 chars is enough
            return 'DEPRECATED' in content
    except:
        return False

def extract_public_names(filepath: Path) -> list[str]:
    """Extract class and public function names from a .py file."""
    names = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                # Class definitions
                m = re.match(r'^class\s+(\w+)\s*[:\(]', line)
                if m:
                    name = m.group(1)
                    if not name.startswith('_'):
                        names.append(name)
                # Top-level function definitions
                m = re.match(r'^def\s+(\w+)\s*\(', line)
                if m:
                    name = m.group(1)
                    if not name.startswith('_') and name not in ('main',):
                        names.append(name)
    except:
        pass
    return names

def generate_init():
    py_files = sorted([f for f in TARGET_DIR.glob("*.py") 
                       if f.name != "__init__.py" and not f.name.startswith("test_")])
    
    imports = []
    all_exports = []
    deprecated_imports = []
    
    for f in py_files:
        mod_name = f.stem
        deprecated = is_deprecated(f)
        names = extract_public_names(f)
        
        if deprecated:
            deprecated_imports.append(f"# [DEPRECATED] from .{mod_name} import {', '.join(names) if names else mod_name}")
            continue
        
        if names:
            names_str = ', '.join(names)
            imports.append(f"from .{mod_name} import {names_str}")
            all_exports.extend(names)
        else:
            imports.append(f"from . import {mod_name}")
            all_exports.append(mod_name)
    
    # Build __init__.py content
    lines = [
        '"""',
        'Trinity Second Brain — Auto-generated module registry.',
        f'Generated by scripts/gen_init.py — {len(py_files)} modules scanned.',
        '"""',
        '',
        '# ── Active Modules ──',
        ''
    ]
    lines.extend(imports)
    lines.append('')
    
    if deprecated_imports:
        lines.append('# ── Deprecated Modules ──')
        lines.extend(deprecated_imports)
        lines.append('')
    
    lines.append('# ── Public API ──')
    lines.append('__all__ = [')
    for name in sorted(set(all_exports)):
        lines.append(f'    "{name}",')
    lines.append(']')
    
    content = '\n'.join(lines) + '\n'
    
    if DRY_RUN:
        print(content)
    else:
        # Backup
        if INIT_FILE.exists():
            bak = INIT_FILE.with_suffix('.py.bak_gen')
            with open(INIT_FILE, 'r', encoding='utf-8') as f:
                orig = f.read()
            with open(bak, 'w', encoding='utf-8') as f:
                f.write(orig)
        
        with open(INIT_FILE, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Generated {INIT_FILE}")
        print(f"  {len(py_files)} modules scanned")
        print(f"  {len(imports)} active imports")
        print(f"  {len(deprecated_imports)} deprecated")
        print(f"  {len(set(all_exports))} public symbols")

if __name__ == "__main__":
    generate_init()
