"""
trinity-config — Trinity configuration wizard
==============================================
Interactive (and non-interactive) configuration for the Trinity memory
system. Collects PostgreSQL connection settings, the API port, the cache
backend and rate-limit tuning, then writes:

* ``C:\\Users\\Administrator\\trinity\\trinity.yaml`` — YAML config. The
  ``pg_password`` value is **never** written in plaintext: an empty password
  (or any password) becomes the placeholder ``${TRINITY_PG_PASSWORD:-postgres}``
  so secrets never end up in git.
* ``C:\\Users\\Administrator\\.trinity\\.env`` (optional) — real runtime
  values for maintenance scripts, outside the repository. The actual
  password (when supplied) is written here only.

Usage
-----
    python scripts\\trinity_config_cli.py                 # interactive wizard
    python scripts\\trinity_config_cli.py --show          # masked current config
    python scripts\\trinity_config_cli.py --apply "{...}" # non-interactive apply

``--apply`` accepts a JSON object (keys may be bare or ``TRINITY_``-prefixed)::

    {
      "pg_host": "127.0.0.1", "pg_port": 5432, "pg_db": "trinity",
      "pg_user": "postgres", "pg_password": null,
      "api_port": 8001, "cache_backend": "off",
      "rate_limit_rate": 60, "rate_limit_burst": 120
    }

Only the Python standard library is used (argparse + json); a tiny
indentation-based YAML reader/writer is bundled so no third-party yaml
package is required.
"""

import argparse
import getpass
import json
import os
import re
import sys
from pathlib import Path

# ── paths / defaults ─────────────────────────────────────────────────────
DEFAULT_CONFIG = Path(r"C:\Users\Administrator\trinity\trinity.yaml")
DEFAULT_ENV_FILE = Path(r"C:\Users\Administrator\.trinity\.env")

PG_PASSWORD_PLACEHOLDER = "${TRINITY_PG_PASSWORD:-postgres}"

CACHE_BACKEND_CHOICES = ("off", "memory", "redis")

DEFAULTS = {
    "pg_host": "127.0.0.1",
    "pg_port": 5432,
    "pg_db": "trinity",
    "pg_user": "postgres",
    "pg_password": "",
    "api_port": 8001,
    "cache_backend": "off",
    "rate_limit_rate": 60,
    "rate_limit_burst": 120,
}

ALLOWED_KEYS = set(DEFAULTS)

# Canonical structure used when no existing yaml is readable.
TEMPLATE = {
    "storage": {
        "db_type": "postgresql",
        "path": "./data",
        "pg_min_conn": 1,
        "pg_max_conn": 10,
    },
    "server": {
        "mcp": {"transport": "stdio", "port": 8000, "host": "0.0.0.0"},
        "api": {"host": "0.0.0.0"},
    },
    "guardian": {"enabled": True, "tiers": "all", "blocking_policy": "first_fail"},
    "benchmark": {"mock_personas": 3, "mock_top_k": 10, "default_top_k": 5},
    "runtime": {"cache_backend": "off", "rate_limit": {"rate": 60, "burst": 120}},
}

# path "a.b.c" -> comment line emitted right before that key
COMMENTS = {
    "storage.pg_password": "# 密码占位符（不落明文）；真实密码写入 ~/.trinity/.env 的 TRINITY_PG_PASSWORD",
    "runtime.cache_backend": "# TRINITY_CACHE_BACKEND: off | memory | redis",
    "runtime.rate_limit": "# TRINITY_RATE_LIMIT_RATE / TRINITY_RATE_LIMIT_BURST",
}

HEADER = (
    "# Trinity Configuration — generated by trinity-config CLI\n"
    "# ============================================================\n"
    "# PostgreSQL storage + API/MCP server settings.\n"
    "# pg_password is a placeholder: the real password lives in\n"
    "# C:\\Users\\Administrator\\.trinity\\.env (TRINITY_PG_PASSWORD).\n"
    "# Never commit plaintext secrets.\n"
)

MASKED_KEY_HINTS = ("password", "secret", "token", "apikey")


# ── minimal yaml reader (no third-party dependency) ──────────────────────
def _coerce_scalar(value: str):
    value = value.strip()
    if not value:
        return ""
    if value.startswith('"') and value.endswith('"'):
        return value[1:-1].replace('\\"', '"')
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1].replace("''", "'")
    low = value.lower()
    if low == "true":
        return True
    if low == "false":
        return False
    if low in ("null", "~"):
        return None
    try:
        return int(value)
    except ValueError:
        pass
    try:
        return float(value)
    except ValueError:
        pass
    return value


def parse_yaml_simple(text: str):
    """Parse a small indentation-based YAML subset into nested dicts.

    Returns None when the text cannot be parsed. Only plain key: value
    mappings, comments and blank lines are supported.
    """
    root: dict = {}
    stack = [(-1, root)]
    try:
        for raw in text.splitlines():
            line = raw.rstrip()
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if ":" not in stripped:
                continue
            indent = len(line) - len(line.lstrip(" "))
            content = stripped
            key, _, value = content.partition(":")
            key = key.strip().strip('"\'')
            value = value.strip()
            # drop trailing inline comment ("  # ...")
            value = re.sub(r"\s+#.*$", "", value).strip()
            while stack and indent <= stack[-1][0]:
                stack.pop()
            parent = stack[-1][1] if stack else root
            if value == "":
                node: dict = {}
                parent[key] = node
                stack.append((indent, node))
            else:
                parent[key] = _coerce_scalar(value)
        return root
    except Exception:  # noqa: BLE001 — caller decides what to do
        return None


# ── yaml writer ──────────────────────────────────────────────────────────
def _yaml_scalar(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    value = str(value)
    # quote only when the plain form would be ambiguous
    if value == "":
        return '""'
    if re.fullmatch(r"[A-Za-z0-9_./:${}@+\-,]+", value):
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def serialize_yaml(data: dict) -> str:
    lines = [HEADER.rstrip("\n")]

    def _emit(node: dict, indent: int, prefix: str):
        for key, value in node.items():
            pad = "  " * indent
            path = f"{prefix}.{key}" if prefix else key
            comment = COMMENTS.get(path)
            if comment:
                lines.append(f"{pad}{comment}")
            if isinstance(value, dict):
                lines.append(f"{pad}{key}:")
                _emit(value, indent + 1, path)
            elif isinstance(value, (list, tuple)):
                lines.append(f"{pad}{key}:")
                for item in value:
                    lines.append(f"{pad}  - {_yaml_scalar(item)}")
            else:
                lines.append(f"{pad}{key}: {_yaml_scalar(value)}")

    _emit(data, 0, "")
    return "\n".join(lines) + "\n"


def _deep_merge(base: dict, override: dict) -> dict:
    """Recursively merge ``override`` into ``base`` (returns base)."""
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _deep_merge(base[key], value)
        else:
            base[key] = value
    return base


# ── .env writer ──────────────────────────────────────────────────────────
def write_env_file(path: Path, values: dict) -> str:
    """Write runtime values to a dotenv file (outside the repo)."""
    lines = [
        "# Trinity runtime environment — generated by trinity-config (outside git)",
        f"TRINITY_PG_HOST={values['pg_host']}",
        f"TRINITY_PG_PORT={values['pg_port']}",
        f"TRINITY_PG_DB={values['pg_db']}",
        f"TRINITY_PG_USER={values['pg_user']}",
        f"TRINITY_API_PORT={values['api_port']}",
        f"TRINITY_CACHE_BACKEND={values['cache_backend']}",
        f"TRINITY_RATE_LIMIT_RATE={values['rate_limit_rate']}",
        f"TRINITY_RATE_LIMIT_BURST={values['rate_limit_burst']}",
    ]
    if values.get("pg_password"):
        lines.append(f"TRINITY_PG_PASSWORD={values['pg_password']}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return "\n".join(lines) + "\n"


# ── value handling ───────────────────────────────────────────────────────
def _normalize_key(key: str) -> str:
    key = key.strip().lower()
    if key.startswith("trinity_"):
        key = key[len("trinity_"):]
    return key


def _coerce_values(raw: dict) -> dict:
    values = dict(DEFAULTS)
    for key, value in raw.items():
        norm = _normalize_key(key)
        if norm not in ALLOWED_KEYS:
            print(f"[warn] ignoring unknown key: {key}", file=sys.stderr)
            continue
        if value is None:
            values[norm] = ""
            continue
        if isinstance(value, str):
            value = value.strip()
            if value.lower() == "null":
                value = ""
        if norm in ("pg_port", "api_port", "rate_limit_rate", "rate_limit_burst"):
            try:
                value = int(value)
            except (TypeError, ValueError):
                raise ValueError(f"field '{norm}' must be an integer, got {value!r}")
        values[norm] = value
    return values


def validate(values: dict) -> list:
    errors = []
    for field in ("pg_port", "api_port"):
        if not (1 <= int(values[field]) <= 65535):
            errors.append(f"{field} must be in 1..65535 (got {values[field]})")
    if values["cache_backend"] not in CACHE_BACKEND_CHOICES:
        errors.append(
            f"cache_backend must be one of {', '.join(CACHE_BACKEND_CHOICES)} "
            f"(got {values['cache_backend']!r})"
        )
    for field in ("rate_limit_rate", "rate_limit_burst"):
        if int(values[field]) <= 0:
            errors.append(f"{field} must be a positive integer (got {values[field]})")
    return errors


# ── config assembly ──────────────────────────────────────────────────────
def build_config(values: dict, existing: dict = None) -> dict:
    """Merge collected values over the existing (parsed) config structure."""
    cfg = dict(TEMPLATE)
    if isinstance(existing, dict):
        cfg = _deep_merge(cfg, existing)
    override = {
        "storage": {
            "db_type": "postgresql",
            "pg_host": values["pg_host"],
            "pg_port": values["pg_port"],
            "pg_db": values["pg_db"],
            "pg_user": values["pg_user"],
            # never plaintext: real password only in the .env file
            "pg_password": PG_PASSWORD_PLACEHOLDER,
        },
        "server": {"api": {"port": values["api_port"]}},
        "runtime": {
            "cache_backend": values["cache_backend"],
            "rate_limit": {
                "rate": values["rate_limit_rate"],
                "burst": values["rate_limit_burst"],
            },
        },
    }
    return _deep_merge(cfg, override)


# ── actions ──────────────────────────────────────────────────────────────
def _write_config(values: dict, config_path: Path, env_path: Path, write_env: bool) -> int:
    try:
        existing = None
        if config_path.exists():
            existing = parse_yaml_simple(config_path.read_text(encoding="utf-8"))
        cfg = build_config(values, existing)
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(serialize_yaml(cfg), encoding="utf-8")
        if write_env:
            write_env_file(env_path, values)
        print(f"[OK] wrote {config_path}")
        print(f"[OK] password placeholder {PG_PASSWORD_PLACEHOLDER} in yaml — plaintext never written")
        if values.get("pg_password"):
            print(f"[OK] real password stored in {env_path} (outside git)")
        elif write_env:
            print(f"[i] no password supplied — {env_path} has no TRINITY_PG_PASSWORD")
        return 0
    except OSError as exc:
        print(f"[ERROR] cannot write config: {exc}", file=sys.stderr)
        return 1


def cmd_apply(args) -> int:
    try:
        raw = json.loads(args.apply)
    except json.JSONDecodeError as exc:
        print(f"[ERROR] --apply expects valid JSON: {exc}", file=sys.stderr)
        return 1
    if not isinstance(raw, dict):
        print("[ERROR] --apply expects a JSON object", file=sys.stderr)
        return 1
    try:
        values = _coerce_values(raw)
    except ValueError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1
    errors = validate(values)
    if errors:
        for err in errors:
            print(f"[ERROR] {err}", file=sys.stderr)
        return 1
    return _write_config(
        values,
        Path(args.config),
        Path(args.env),
        write_env=not args.no_env,
    )


def _print_tree(node: dict, indent: int = 0) -> None:
    for key, value in node.items():
        pad = "  " * indent
        if isinstance(value, dict):
            print(f"{pad}{key}:")
            _print_tree(value, indent + 1)
        else:
            if any(hint in str(key).lower() for hint in MASKED_KEY_HINTS):
                shown = "**** (masked)"
            else:
                shown = _yaml_scalar(value)
            print(f"{pad}{key}: {shown}")


def cmd_show(args) -> int:
    config_path = Path(args.config)
    if not config_path.exists():
        print(f"[ERROR] config not found: {config_path}", file=sys.stderr)
        return 2
    text = config_path.read_text(encoding="utf-8")
    data = parse_yaml_simple(text)
    if data is None:
        print(f"[ERROR] cannot parse {config_path}", file=sys.stderr)
        return 2
    print(f"Trinity config: {config_path}")
    _print_tree(data)
    # environment file status (masked)
    env_path = Path(args.env)
    if env_path.exists():
        env_text = env_path.read_text(encoding="utf-8")
        pw_line = [ln for ln in env_text.splitlines() if ln.startswith("TRINITY_PG_PASSWORD=")]
        status = "set — masked" if pw_line else "not set"
        print(f"Environment file: {env_path} (TRINITY_PG_PASSWORD: {status})")
    else:
        print(f"Environment file: {env_path} (not found)")
    return 0


def cmd_interactive(args) -> int:
    print("=== Trinity configuration wizard ===")
    print("(press Enter to accept the default in brackets)\n")

    def ask(prompt, default):
        raw = input(f"{prompt} [{default}]: ").strip() if default not in (None, "") else input(f"{prompt}: ").strip()
        return raw if raw else default

    values = dict(DEFAULTS)
    values["pg_host"] = ask("PG host", values["pg_host"])
    values["pg_port"] = ask("PG port", values["pg_port"])
    values["pg_db"] = ask("PG database", values["pg_db"])
    values["pg_user"] = ask("PG user", values["pg_user"])
    try:
        pw = getpass.getpass("PG password (empty → env placeholder): ").strip()
    except Exception:  # noqa: BLE001 — e.g. no tty; fall back to input()
        pw = input("PG password (empty → env placeholder): ").strip()
    values["pg_password"] = pw
    values["api_port"] = ask("API port", values["api_port"])
    values["cache_backend"] = ask(
        f"Cache backend ({'/'.join(CACHE_BACKEND_CHOICES)})", values["cache_backend"]
    )
    values["rate_limit_rate"] = ask("Rate limit rate (per second)", values["rate_limit_rate"])
    values["rate_limit_burst"] = ask("Rate limit burst", values["rate_limit_burst"])

    try:
        values = _coerce_values(values)
    except ValueError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1
    errors = validate(values)
    if errors:
        for err in errors:
            print(f"[ERROR] {err}", file=sys.stderr)
        return 1

    write_env = True
    if pw:
        answer = input(f"Write password to {Path(args.env)} (outside git)? [y/N]: ").strip().lower()
        write_env = answer in ("y", "yes")
    return _write_config(
        values,
        Path(args.config),
        Path(args.env),
        write_env=write_env,
    )


# ── entry point ──────────────────────────────────────────────────────────
def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="trinity-config",
        description="Trinity configuration wizard (yaml + optional .env).",
    )
    parser.add_argument("--show", action="store_true", help="Show current config with masked secrets")
    parser.add_argument("--apply", metavar="JSON", help="Apply config from a JSON object (non-interactive)")
    parser.add_argument(
        "--config", default=str(DEFAULT_CONFIG),
        help=f"target yaml file (default {DEFAULT_CONFIG})",
    )
    parser.add_argument(
        "--env", default=str(DEFAULT_ENV_FILE),
        help=f"target env file (default {DEFAULT_ENV_FILE})",
    )
    parser.add_argument(
        "--no-env", action="store_true",
        help="do not write the .env file",
    )
    args = parser.parse_args(argv)

    if args.show:
        return cmd_show(args)
    if args.apply is not None:
        return cmd_apply(args)
    return cmd_interactive(args)


if __name__ == "__main__":
    sys.exit(main())
